name: Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SSH_KEY }}
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H 51.81.86.146 >> ~/.ssh/known_hosts
        
      - name: Rebuild
        run: ssh prod@51.81.86.146 -p 1023 /var/deaconn/start.sh
    
